# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model/LocationServiceResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from model import ServerLocationsData_pb2 as model_dot_ServerLocationsData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='model/LocationServiceResponse.proto',
  package='V2X.Protobuf',
  syntax='proto3',
  serialized_options=_b('\n0com.eyenet.locationservice.dao.entities.protobufB\034LocationServiceResponseProto'),
  serialized_pb=_b('\n#model/LocationServiceResponse.proto\x12\x0cV2X.Protobuf\x1a\x1fmodel/ServerLocationsData.proto\"\xc9\x01\n\x17LocationServiceResponse\x12?\n\x04type\x18\x01 \x01(\x0e\x32\x31.V2X.Protobuf.LocationServiceResponse.MessageType\x12@\n\x13serverLocationsData\x18\x02 \x01(\x0b\x32!.V2X.Protobuf.ServerLocationsDataH\x00\"#\n\x0bMessageType\x12\x14\n\x10SERVER_LOCATIONS\x10\x00\x42\x06\n\x04\x64\x61taBP\n0com.eyenet.locationservice.dao.entities.protobufB\x1cLocationServiceResponseProtob\x06proto3')
  ,
  dependencies=[model_dot_ServerLocationsData__pb2.DESCRIPTOR,])



_LOCATIONSERVICERESPONSE_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='V2X.Protobuf.LocationServiceResponse.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SERVER_LOCATIONS', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=245,
  serialized_end=280,
)
_sym_db.RegisterEnumDescriptor(_LOCATIONSERVICERESPONSE_MESSAGETYPE)


_LOCATIONSERVICERESPONSE = _descriptor.Descriptor(
  name='LocationServiceResponse',
  full_name='V2X.Protobuf.LocationServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='V2X.Protobuf.LocationServiceResponse.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverLocationsData', full_name='V2X.Protobuf.LocationServiceResponse.serverLocationsData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LOCATIONSERVICERESPONSE_MESSAGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='V2X.Protobuf.LocationServiceResponse.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=87,
  serialized_end=288,
)

_LOCATIONSERVICERESPONSE.fields_by_name['type'].enum_type = _LOCATIONSERVICERESPONSE_MESSAGETYPE
_LOCATIONSERVICERESPONSE.fields_by_name['serverLocationsData'].message_type = model_dot_ServerLocationsData__pb2._SERVERLOCATIONSDATA
_LOCATIONSERVICERESPONSE_MESSAGETYPE.containing_type = _LOCATIONSERVICERESPONSE
_LOCATIONSERVICERESPONSE.oneofs_by_name['data'].fields.append(
  _LOCATIONSERVICERESPONSE.fields_by_name['serverLocationsData'])
_LOCATIONSERVICERESPONSE.fields_by_name['serverLocationsData'].containing_oneof = _LOCATIONSERVICERESPONSE.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['LocationServiceResponse'] = _LOCATIONSERVICERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocationServiceResponse = _reflection.GeneratedProtocolMessageType('LocationServiceResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONSERVICERESPONSE,
  '__module__' : 'model.LocationServiceResponse_pb2'
  # @@protoc_insertion_point(class_scope:V2X.Protobuf.LocationServiceResponse)
  })
_sym_db.RegisterMessage(LocationServiceResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
