# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    List as typing___List,
    Optional as typing___Optional,
    Text as typing___Text,
    Tuple as typing___Tuple,
    cast as typing___cast,
    overload as typing___overload,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
builtin___str = str


class ClientData(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class LocationBearerType(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(cls, name: builtin___str) -> 'ClientData.LocationBearerType': ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List['ClientData.LocationBearerType']: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[builtin___str, 'ClientData.LocationBearerType']]: ...
        PEDESTRIAN = typing___cast('ClientData.LocationBearerType', 0)
        CAR = typing___cast('ClientData.LocationBearerType', 1)
        BIKE = typing___cast('ClientData.LocationBearerType', 2)
    PEDESTRIAN = typing___cast('ClientData.LocationBearerType', 0)
    CAR = typing___cast('ClientData.LocationBearerType', 1)
    BIKE = typing___cast('ClientData.LocationBearerType', 2)

    id = ... # type: typing___Text
    bearing = ... # type: builtin___float
    latitude = ... # type: builtin___float
    velocity = ... # type: builtin___float
    longitude = ... # type: builtin___float
    clientDataType = ... # type: ClientData.LocationBearerType
    timestamp = ... # type: typing___Text
    altitudeValue = ... # type: builtin___float
    altitudeNull = ... # type: builtin___bool
    horizontalAccuracy = ... # type: builtin___float
    verticalAccuracyNull = ... # type: builtin___bool
    verticalAccuracyValue = ... # type: builtin___float
    source = ... # type: typing___Text
    sessionId = ... # type: typing___Text
    maxAcceleration = ... # type: builtin___float
    maxAngularChange = ... # type: builtin___float
    avgAcceleration = ... # type: builtin___float
    avgAngularChange = ... # type: builtin___float
    maxDeceleration = ... # type: builtin___float
    rawHorizontalAccuracyValue = ... # type: builtin___float
    rawHorizontalAccuracyNull = ... # type: builtin___bool

    def __init__(self,
        *,
        id : typing___Optional[typing___Text] = None,
        bearing : typing___Optional[builtin___float] = None,
        latitude : typing___Optional[builtin___float] = None,
        velocity : typing___Optional[builtin___float] = None,
        longitude : typing___Optional[builtin___float] = None,
        clientDataType : typing___Optional[ClientData.LocationBearerType] = None,
        timestamp : typing___Optional[typing___Text] = None,
        altitudeValue : typing___Optional[builtin___float] = None,
        altitudeNull : typing___Optional[builtin___bool] = None,
        horizontalAccuracy : typing___Optional[builtin___float] = None,
        verticalAccuracyNull : typing___Optional[builtin___bool] = None,
        verticalAccuracyValue : typing___Optional[builtin___float] = None,
        source : typing___Optional[typing___Text] = None,
        sessionId : typing___Optional[typing___Text] = None,
        maxAcceleration : typing___Optional[builtin___float] = None,
        maxAngularChange : typing___Optional[builtin___float] = None,
        avgAcceleration : typing___Optional[builtin___float] = None,
        avgAngularChange : typing___Optional[builtin___float] = None,
        maxDeceleration : typing___Optional[builtin___float] = None,
        rawHorizontalAccuracyValue : typing___Optional[builtin___float] = None,
        rawHorizontalAccuracyNull : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> ClientData: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"altitude",u"altitudeNull",u"altitudeValue",u"rawHorizontalAccuracy",u"rawHorizontalAccuracyNull",u"rawHorizontalAccuracyValue",u"verticalAccuracy",u"verticalAccuracyNull",u"verticalAccuracyValue"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"altitude",u"altitudeNull",u"altitudeValue",u"avgAcceleration",u"avgAngularChange",u"bearing",u"clientDataType",u"horizontalAccuracy",u"id",u"latitude",u"longitude",u"maxAcceleration",u"maxAngularChange",u"maxDeceleration",u"rawHorizontalAccuracy",u"rawHorizontalAccuracyNull",u"rawHorizontalAccuracyValue",u"sessionId",u"source",u"timestamp",u"velocity",u"verticalAccuracy",u"verticalAccuracyNull",u"verticalAccuracyValue"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"altitude",b"altitude",u"altitudeNull",b"altitudeNull",u"altitudeValue",b"altitudeValue",u"rawHorizontalAccuracy",b"rawHorizontalAccuracy",u"rawHorizontalAccuracyNull",b"rawHorizontalAccuracyNull",u"rawHorizontalAccuracyValue",b"rawHorizontalAccuracyValue",u"verticalAccuracy",b"verticalAccuracy",u"verticalAccuracyNull",b"verticalAccuracyNull",u"verticalAccuracyValue",b"verticalAccuracyValue"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"altitude",b"altitude",u"altitudeNull",b"altitudeNull",u"altitudeValue",b"altitudeValue",u"avgAcceleration",b"avgAcceleration",u"avgAngularChange",b"avgAngularChange",u"bearing",b"bearing",u"clientDataType",b"clientDataType",u"horizontalAccuracy",b"horizontalAccuracy",u"id",b"id",u"latitude",b"latitude",u"longitude",b"longitude",u"maxAcceleration",b"maxAcceleration",u"maxAngularChange",b"maxAngularChange",u"maxDeceleration",b"maxDeceleration",u"rawHorizontalAccuracy",b"rawHorizontalAccuracy",u"rawHorizontalAccuracyNull",b"rawHorizontalAccuracyNull",u"rawHorizontalAccuracyValue",b"rawHorizontalAccuracyValue",u"sessionId",b"sessionId",u"source",b"source",u"timestamp",b"timestamp",u"velocity",b"velocity",u"verticalAccuracy",b"verticalAccuracy",u"verticalAccuracyNull",b"verticalAccuracyNull",u"verticalAccuracyValue",b"verticalAccuracyValue"]) -> None: ...
    @typing___overload
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"altitude",b"altitude"]) -> typing_extensions___Literal["altitudeValue","altitudeNull"]: ...
    @typing___overload
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"rawHorizontalAccuracy",b"rawHorizontalAccuracy"]) -> typing_extensions___Literal["rawHorizontalAccuracyValue","rawHorizontalAccuracyNull"]: ...
    @typing___overload
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"verticalAccuracy",b"verticalAccuracy"]) -> typing_extensions___Literal["verticalAccuracyNull","verticalAccuracyValue"]: ...

class ClientDataList(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def data(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[ClientData]: ...

    def __init__(self,
        *,
        data : typing___Optional[typing___Iterable[ClientData]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> ClientDataList: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"data"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"data",b"data"]) -> None: ...
