# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model/ClientDataExtension.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from src.proto import ClientData_pb2 as model_dot_ClientData__pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='model/ClientDataExtension.proto',
    package='V2X.Protobuf',
    syntax='proto3',
    serialized_options=_b('\n#com.eyenet.common.entities.protobufB\030ClientDataExtensionProto'),
    serialized_pb=_b(
        '\n\x1fmodel/ClientDataExtension.proto\x12\x0cV2X.Protobuf\x1a\x16model/ClientData.proto\"f\n\x13\x43lientDataExtension\x12,\n\nclientData\x18\x01 \x01(\x0b\x32\x18.V2X.Protobuf.ClientData\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x15\n\rserverNtpTime\x18\x03 \x01(\x03\"J\n\x17\x43lientDataExtensionList\x12/\n\x04list\x18\x01 \x03(\x0b\x32!.V2X.Protobuf.ClientDataExtensionB?\n#com.eyenet.common.entities.protobufB\x18\x43lientDataExtensionProtob\x06proto3')
    ,
    dependencies=[model_dot_ClientData__pb2.DESCRIPTOR, ])

_CLIENTDATAEXTENSION = _descriptor.Descriptor(
    name='ClientDataExtension',
    full_name='V2X.Protobuf.ClientDataExtension',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='clientData', full_name='V2X.Protobuf.ClientDataExtension.clientData', index=0,
            number=1, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='ip', full_name='V2X.Protobuf.ClientDataExtension.ip', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='serverNtpTime', full_name='V2X.Protobuf.ClientDataExtension.serverNtpTime', index=2,
            number=3, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=73,
    serialized_end=175,
)

_CLIENTDATAEXTENSIONLIST = _descriptor.Descriptor(
    name='ClientDataExtensionList',
    full_name='V2X.Protobuf.ClientDataExtensionList',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='list', full_name='V2X.Protobuf.ClientDataExtensionList.list', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=177,
    serialized_end=251,
)

_CLIENTDATAEXTENSION.fields_by_name['clientData'].message_type = model_dot_ClientData__pb2._CLIENTDATA
_CLIENTDATAEXTENSIONLIST.fields_by_name['list'].message_type = _CLIENTDATAEXTENSION
DESCRIPTOR.message_types_by_name['ClientDataExtension'] = _CLIENTDATAEXTENSION
DESCRIPTOR.message_types_by_name['ClientDataExtensionList'] = _CLIENTDATAEXTENSIONLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientDataExtension = _reflection.GeneratedProtocolMessageType('ClientDataExtension', (_message.Message,), {
    'DESCRIPTOR': _CLIENTDATAEXTENSION,
    '__module__': 'model.ClientDataExtension_pb2'
    # @@protoc_insertion_point(class_scope:V2X.Protobuf.ClientDataExtension)
})
_sym_db.RegisterMessage(ClientDataExtension)

ClientDataExtensionList = _reflection.GeneratedProtocolMessageType('ClientDataExtensionList', (_message.Message,), {
    'DESCRIPTOR': _CLIENTDATAEXTENSIONLIST,
    '__module__': 'model.ClientDataExtension_pb2'
    # @@protoc_insertion_point(class_scope:V2X.Protobuf.ClientDataExtensionList)
})
_sym_db.RegisterMessage(ClientDataExtensionList)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
