# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from src.proto.ClientData_pb2 import (
    ClientData as ClientData_pb2___ClientData,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class ClientDataExtension(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    ip = ... # type: typing___Text
    serverNtpTime = ... # type: builtin___int

    @property
    def clientData(self) -> ClientData_pb2___ClientData: ...

    def __init__(self,
        *,
        clientData : typing___Optional[ClientData_pb2___ClientData] = None,
        ip : typing___Optional[typing___Text] = None,
        serverNtpTime : typing___Optional[builtin___int] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> ClientDataExtension: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"clientData"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"clientData",u"ip",u"serverNtpTime"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"clientData",b"clientData"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"clientData",b"clientData",u"ip",b"ip",u"serverNtpTime",b"serverNtpTime"]) -> None: ...

class ClientDataExtensionList(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def list(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[ClientDataExtension]: ...

    def __init__(self,
        *,
        list : typing___Optional[typing___Iterable[ClientDataExtension]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> ClientDataExtensionList: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"list"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"list",b"list"]) -> None: ...
