# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from src.proto.ClientData_pb2 import (
    ClientData as ClientData_pb2___ClientData,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class ClientLocationData(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    debugMode = ... # type: builtin___bool
    notifyMe = ... # type: builtin___bool
    notifyOthers = ... # type: builtin___bool

    @property
    def clientData(self) -> ClientData_pb2___ClientData: ...

    def __init__(self,
        *,
        clientData : typing___Optional[ClientData_pb2___ClientData] = None,
        debugMode : typing___Optional[builtin___bool] = None,
        notifyMe : typing___Optional[builtin___bool] = None,
        notifyOthers : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> ClientLocationData: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"clientData"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"clientData",u"debugMode",u"notifyMe",u"notifyOthers"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"clientData",b"clientData"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"clientData",b"clientData",u"debugMode",b"debugMode",u"notifyMe",b"notifyMe",u"notifyOthers",b"notifyOthers"]) -> None: ...
