# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model/ClientData.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='model/ClientData.proto',
    package='V2X.Protobuf',
    syntax='proto3',
    serialized_options=_b('\n#com.eyenet.common.entities.protobufB\020ClientDataProtos'),
    serialized_pb=_b(
        '\n\x16model/ClientData.proto\x12\x0cV2X.Protobuf\"\xa5\x05\n\nClientData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x65\x61ring\x18\x02 \x01(\x01\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x10\n\x08velocity\x18\x04 \x01(\x01\x12\x11\n\tlongitude\x18\x05 \x01(\x01\x12\x43\n\x0e\x63lientDataType\x18\x06 \x01(\x0e\x32+.V2X.Protobuf.ClientData.LocationBearerType\x12\x11\n\ttimestamp\x18\x07 \x01(\t\x12\x17\n\raltitudeValue\x18\x08 \x01(\x01H\x00\x12\x16\n\x0c\x61ltitudeNull\x18\t \x01(\x08H\x00\x12\x1a\n\x12horizontalAccuracy\x18\n \x01(\x01\x12\x1e\n\x14verticalAccuracyNull\x18\x0b \x01(\x08H\x01\x12\x1f\n\x15verticalAccuracyValue\x18\x0c \x01(\x01H\x01\x12\x0e\n\x06source\x18\r \x01(\t\x12\x11\n\tsessionId\x18\x0e \x01(\t\x12\x17\n\x0fmaxAcceleration\x18\x0f \x01(\x01\x12\x18\n\x10maxAngularChange\x18\x10 \x01(\x01\x12\x17\n\x0f\x61vgAcceleration\x18\x11 \x01(\x01\x12\x18\n\x10\x61vgAngularChange\x18\x12 \x01(\x01\x12\x17\n\x0fmaxDeceleration\x18\x13 \x01(\x01\x12$\n\x1arawHorizontalAccuracyValue\x18\x14 \x01(\x01H\x02\x12#\n\x19rawHorizontalAccuracyNull\x18\x15 \x01(\x08H\x02\"7\n\x12LocationBearerType\x12\x0e\n\nPEDESTRIAN\x10\x00\x12\x07\n\x03\x43\x41R\x10\x01\x12\x08\n\x04\x42IKE\x10\x02\x42\n\n\x08\x61ltitudeB\x12\n\x10verticalAccuracyB\x17\n\x15rawHorizontalAccuracy\"8\n\x0e\x43lientDataList\x12&\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x18.V2X.Protobuf.ClientDataB7\n#com.eyenet.common.entities.protobufB\x10\x43lientDataProtosb\x06proto3')
)

_CLIENTDATA_LOCATIONBEARERTYPE = _descriptor.EnumDescriptor(
    name='LocationBearerType',
    full_name='V2X.Protobuf.ClientData.LocationBearerType',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='PEDESTRIAN', index=0, number=0,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='CAR', index=1, number=1,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='BIKE', index=2, number=2,
            serialized_options=None,
            type=None),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=606,
    serialized_end=661,
)
_sym_db.RegisterEnumDescriptor(_CLIENTDATA_LOCATIONBEARERTYPE)

_CLIENTDATA = _descriptor.Descriptor(
    name='ClientData',
    full_name='V2X.Protobuf.ClientData',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='V2X.Protobuf.ClientData.id', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='bearing', full_name='V2X.Protobuf.ClientData.bearing', index=1,
            number=2, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='latitude', full_name='V2X.Protobuf.ClientData.latitude', index=2,
            number=3, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='velocity', full_name='V2X.Protobuf.ClientData.velocity', index=3,
            number=4, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='longitude', full_name='V2X.Protobuf.ClientData.longitude', index=4,
            number=5, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='clientDataType', full_name='V2X.Protobuf.ClientData.clientDataType', index=5,
            number=6, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='timestamp', full_name='V2X.Protobuf.ClientData.timestamp', index=6,
            number=7, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='altitudeValue', full_name='V2X.Protobuf.ClientData.altitudeValue', index=7,
            number=8, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='altitudeNull', full_name='V2X.Protobuf.ClientData.altitudeNull', index=8,
            number=9, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='horizontalAccuracy', full_name='V2X.Protobuf.ClientData.horizontalAccuracy', index=9,
            number=10, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='verticalAccuracyNull', full_name='V2X.Protobuf.ClientData.verticalAccuracyNull', index=10,
            number=11, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='verticalAccuracyValue', full_name='V2X.Protobuf.ClientData.verticalAccuracyValue', index=11,
            number=12, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='source', full_name='V2X.Protobuf.ClientData.source', index=12,
            number=13, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='sessionId', full_name='V2X.Protobuf.ClientData.sessionId', index=13,
            number=14, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='maxAcceleration', full_name='V2X.Protobuf.ClientData.maxAcceleration', index=14,
            number=15, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='maxAngularChange', full_name='V2X.Protobuf.ClientData.maxAngularChange', index=15,
            number=16, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='avgAcceleration', full_name='V2X.Protobuf.ClientData.avgAcceleration', index=16,
            number=17, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='avgAngularChange', full_name='V2X.Protobuf.ClientData.avgAngularChange', index=17,
            number=18, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='maxDeceleration', full_name='V2X.Protobuf.ClientData.maxDeceleration', index=18,
            number=19, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='rawHorizontalAccuracyValue', full_name='V2X.Protobuf.ClientData.rawHorizontalAccuracyValue', index=19,
            number=20, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='rawHorizontalAccuracyNull', full_name='V2X.Protobuf.ClientData.rawHorizontalAccuracyNull', index=20,
            number=21, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
        _CLIENTDATA_LOCATIONBEARERTYPE,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name='altitude', full_name='V2X.Protobuf.ClientData.altitude',
            index=0, containing_type=None, fields=[]),
        _descriptor.OneofDescriptor(
            name='verticalAccuracy', full_name='V2X.Protobuf.ClientData.verticalAccuracy',
            index=1, containing_type=None, fields=[]),
        _descriptor.OneofDescriptor(
            name='rawHorizontalAccuracy', full_name='V2X.Protobuf.ClientData.rawHorizontalAccuracy',
            index=2, containing_type=None, fields=[]),
    ],
    serialized_start=41,
    serialized_end=718,
)

_CLIENTDATALIST = _descriptor.Descriptor(
    name='ClientDataList',
    full_name='V2X.Protobuf.ClientDataList',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='data', full_name='V2X.Protobuf.ClientDataList.data', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=720,
    serialized_end=776,
)

_CLIENTDATA.fields_by_name['clientDataType'].enum_type = _CLIENTDATA_LOCATIONBEARERTYPE
_CLIENTDATA_LOCATIONBEARERTYPE.containing_type = _CLIENTDATA
_CLIENTDATA.oneofs_by_name['altitude'].fields.append(_CLIENTDATA.fields_by_name['altitudeValue'])
_CLIENTDATA.fields_by_name['altitudeValue'].containing_oneof = _CLIENTDATA.oneofs_by_name['altitude']
_CLIENTDATA.oneofs_by_name['altitude'].fields.append(_CLIENTDATA.fields_by_name['altitudeNull'])
_CLIENTDATA.fields_by_name['altitudeNull'].containing_oneof = _CLIENTDATA.oneofs_by_name['altitude']
_CLIENTDATA.oneofs_by_name['verticalAccuracy'].fields.append(_CLIENTDATA.fields_by_name['verticalAccuracyNull'])
_CLIENTDATA.fields_by_name['verticalAccuracyNull'].containing_oneof = _CLIENTDATA.oneofs_by_name['verticalAccuracy']
_CLIENTDATA.oneofs_by_name['verticalAccuracy'].fields.append(_CLIENTDATA.fields_by_name['verticalAccuracyValue'])
_CLIENTDATA.fields_by_name['verticalAccuracyValue'].containing_oneof = _CLIENTDATA.oneofs_by_name['verticalAccuracy']
_CLIENTDATA.oneofs_by_name['rawHorizontalAccuracy'].fields.append(_CLIENTDATA.fields_by_name['rawHorizontalAccuracyValue'])
_CLIENTDATA.fields_by_name['rawHorizontalAccuracyValue'].containing_oneof = _CLIENTDATA.oneofs_by_name['rawHorizontalAccuracy']
_CLIENTDATA.oneofs_by_name['rawHorizontalAccuracy'].fields.append(_CLIENTDATA.fields_by_name['rawHorizontalAccuracyNull'])
_CLIENTDATA.fields_by_name['rawHorizontalAccuracyNull'].containing_oneof = _CLIENTDATA.oneofs_by_name['rawHorizontalAccuracy']
_CLIENTDATALIST.fields_by_name['data'].message_type = _CLIENTDATA
DESCRIPTOR.message_types_by_name['ClientData'] = _CLIENTDATA
DESCRIPTOR.message_types_by_name['ClientDataList'] = _CLIENTDATALIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientData = _reflection.GeneratedProtocolMessageType('ClientData', (_message.Message,), {
    'DESCRIPTOR': _CLIENTDATA,
    '__module__': 'model.ClientData_pb2'
    # @@protoc_insertion_point(class_scope:V2X.Protobuf.ClientData)
})
_sym_db.RegisterMessage(ClientData)

ClientDataList = _reflection.GeneratedProtocolMessageType('ClientDataList', (_message.Message,), {
    'DESCRIPTOR': _CLIENTDATALIST,
    '__module__': 'model.ClientData_pb2'
    # @@protoc_insertion_point(class_scope:V2X.Protobuf.ClientDataList)
})
_sym_db.RegisterMessage(ClientDataList)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
