# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from src.proto.ClientLocationData_pb2 import (
    ClientLocationData as ClientLocationData_pb2___ClientLocationData,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    List as typing___List,
    Optional as typing___Optional,
    Tuple as typing___Tuple,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
builtin___str = str


class LocationServiceRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class MessageType(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(cls, name: builtin___str) -> 'LocationServiceRequest.MessageType': ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List['LocationServiceRequest.MessageType']: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[builtin___str, 'LocationServiceRequest.MessageType']]: ...
        CLIENT_LOCATION = typing___cast('LocationServiceRequest.MessageType', 0)
    CLIENT_LOCATION = typing___cast('LocationServiceRequest.MessageType', 0)

    type = ... # type: LocationServiceRequest.MessageType

    @property
    def clientLocationData(self) -> ClientLocationData_pb2___ClientLocationData: ...

    def __init__(self,
        *,
        type : typing___Optional[LocationServiceRequest.MessageType] = None,
        clientLocationData : typing___Optional[ClientLocationData_pb2___ClientLocationData] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> LocationServiceRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"clientLocationData",u"data"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"clientLocationData",u"data",u"type"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"clientLocationData",b"clientLocationData",u"data",b"data"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"clientLocationData",b"clientLocationData",u"data",b"data",u"type",b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"data",b"data"]) -> typing_extensions___Literal["clientLocationData"]: ...
