# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model/LocationServiceRequest.proto

import sys
from src.proto import ClientLocationData_pb2 as ClientLocationData__pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='model/LocationServiceRequest.proto',
    package='V2X.Protobuf',
    syntax='proto3',
    serialized_options=_b('\n0com.eyenet.locationservice.dao.entities.protobufB\033LocationServiceRequestProto'),
    serialized_pb=_b(
        '\n\"model/LocationServiceRequest.proto\x12\x0cV2X.Protobuf\x1a\x18\x43lientLocationData.proto\"\xc4\x01\n\x16LocationServiceRequest\x12>\n\x04type\x18\x01 \x01(\x0e\x32\x30.V2X.Protobuf.LocationServiceRequest.MessageType\x12>\n\x12\x63lientLocationData\x18\x02 \x01(\x0b\x32 .V2X.Protobuf.ClientLocationDataH\x00\"\"\n\x0bMessageType\x12\x13\n\x0f\x43LIENT_LOCATION\x10\x00\x42\x06\n\x04\x64\x61taBO\n0com.eyenet.locationservice.dao.entities.protobufB\x1bLocationServiceRequestProtob\x06proto3'),
    dependencies=[ClientLocationData__pb2.DESCRIPTOR, ])

_LOCATIONSERVICEREQUEST_MESSAGETYPE = _descriptor.EnumDescriptor(
    name='MessageType',
    full_name='V2X.Protobuf.LocationServiceRequest.MessageType',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='CLIENT_LOCATION', index=0, number=0,
            serialized_options=None,
            type=None),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=233,
    serialized_end=267,
)
_sym_db.RegisterEnumDescriptor(_LOCATIONSERVICEREQUEST_MESSAGETYPE)

_LOCATIONSERVICEREQUEST = _descriptor.Descriptor(
    name='LocationServiceRequest',
    full_name='V2X.Protobuf.LocationServiceRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='type', full_name='V2X.Protobuf.LocationServiceRequest.type', index=0,
            number=1, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='clientLocationData', full_name='V2X.Protobuf.LocationServiceRequest.clientLocationData', index=1,
            number=2, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[
        _LOCATIONSERVICEREQUEST_MESSAGETYPE,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name='data', full_name='V2X.Protobuf.LocationServiceRequest.data',
            index=0, containing_type=None, fields=[]),
    ],
    serialized_start=79,
    serialized_end=275,
)

_LOCATIONSERVICEREQUEST.fields_by_name['type'].enum_type = _LOCATIONSERVICEREQUEST_MESSAGETYPE
_LOCATIONSERVICEREQUEST.fields_by_name['clientLocationData'].message_type = ClientLocationData__pb2._CLIENTLOCATIONDATA
_LOCATIONSERVICEREQUEST_MESSAGETYPE.containing_type = _LOCATIONSERVICEREQUEST
_LOCATIONSERVICEREQUEST.oneofs_by_name['data'].fields.append(_LOCATIONSERVICEREQUEST.fields_by_name['clientLocationData'])
_LOCATIONSERVICEREQUEST.fields_by_name['clientLocationData'].containing_oneof = _LOCATIONSERVICEREQUEST.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['LocationServiceRequest'] = _LOCATIONSERVICEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocationServiceRequest = _reflection.GeneratedProtocolMessageType('LocationServiceRequest', (_message.Message,), {
    'DESCRIPTOR': _LOCATIONSERVICEREQUEST,
    '__module__': 'model.LocationServiceRequest_pb2'
    # @@protoc_insertion_point(class_scope:V2X.Protobuf.LocationServiceRequest)
})
_sym_db.RegisterMessage(LocationServiceRequest)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
