# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model/ServerLocationsData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from src.proto import ClientData_pb2 as model_dot_ClientData__pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='model/ServerLocationsData.proto',
  package='V2X.Protobuf',
  syntax='proto3',
  serialized_options=_b('\n0com.eyenet.locationservice.dao.entities.protobufB\027ServerLocationDataProto'),
  serialized_pb=_b('\n\x1fmodel/ServerLocationsData.proto\x12\x0cV2X.Protobuf\x1a\x16model/ClientData.proto\"H\n\x13ServerLocationsData\x12\x31\n\x0b\x63lientDatas\x18\x01 \x01(\x0b\x32\x1c.V2X.Protobuf.ClientDataListBK\n0com.eyenet.locationservice.dao.entities.protobufB\x17ServerLocationDataProtob\x06proto3')
  ,
  dependencies=[model_dot_ClientData__pb2.DESCRIPTOR,])

_SERVERLOCATIONSDATA = _descriptor.Descriptor(
  name='ServerLocationsData',
  full_name='V2X.Protobuf.ServerLocationsData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientDatas', full_name='V2X.Protobuf.ServerLocationsData.clientDatas', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[],
  nested_types=[],
  enum_types=[],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[],
  serialized_start=73,
  serialized_end=145,
)

_SERVERLOCATIONSDATA.fields_by_name['clientDatas'].message_type = model_dot_ClientData__pb2._CLIENTDATALIST
DESCRIPTOR.message_types_by_name['ServerLocationsData'] = _SERVERLOCATIONSDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerLocationsData = _reflection.GeneratedProtocolMessageType('ServerLocationsData', (_message.Message,), {
  'DESCRIPTOR' : _SERVERLOCATIONSDATA,
  '__module__' : 'model.ServerLocationsData_pb2'
  # @@protoc_insertion_point(class_scope:V2X.Protobuf.ServerLocationsData)
  })
_sym_db.RegisterMessage(ServerLocationsData)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
