# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from src.proto.ClientData_pb2 import (
    ClientDataList as ClientData_pb2___ClientDataList,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class ServerLocationsData(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def clientDatas(self) -> ClientData_pb2___ClientDataList: ...

    def __init__(self,
        *,
        clientDatas : typing___Optional[ClientData_pb2___ClientDataList] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> ServerLocationsData: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"clientDatas"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"clientDatas"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"clientDatas",b"clientDatas"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"clientDatas",b"clientDatas"]) -> None: ...
